export const CLOCK_CONSTANTS = {
  DEGREES_PER_HOUR: 30,
  DEGREES_PER_MINUTE: 6,
  DEGREES_PER_SECOND: 6,
  MINUTES_PER_HOUR: 60,
  HOURS_PER_DAY: 24,
  HOURS_PER_HALF_DAY: 12,
  SVG_COORDINATE_OFFSET: -90,
  CIRCLE_DEGREES: 360,
  CROSS_TWELVE_THRESHOLD: 180,
  MINUTE_ANGLE_MULTIPLIER: 0.5, // 時針の1分あたりの角度
  TOTAL_MINUTES_PER_12_HOURS: 720,
} as const

export const CLOCK_DIMENSIONS = {
  WIDTH: 320,
  HEIGHT: 320,
  RADIUS: 150,
  CENTER: { x: 160, y: 160 },
  HOUR_HAND_LENGTH: 80,
  MINUTE_HAND_LENGTH: 110,
  SECOND_HAND_LENGTH: 120,
  HOUR_MARK_OUTER: 140,
  HOUR_MARK_INNER: 125,
  MINUTE_MARK_OUTER: 140,
  MINUTE_MARK_INNER: 133,
  NUMBER_RADIUS: 120,
  CENTER_DOT_RADIUS: 10,
} as const

export const ANIMATION_CONSTANTS = {
  CLOCK_UPDATE_INTERVAL: 1000, // 1秒
  TRANSITION_DURATION: 300, // 0.3秒
  HOVER_TRANSFORM_SCALE: 1.1,
} as const

export const BREAKPOINTS = {
  SM: 640,
  MD: 768,
  LG: 1024,
} as const